# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java
env: flex
runtime_config:
  operating_system: ubuntu22
  runtime_version: 17

manual_scaling:
  instances: 1

env_variables:
  SPRING_PROFILES_ACTIVE: "prod"
  ANTHROPIC_API_KEY: "projects/sopra-fs25-group-46-server/secrets/ANTHROPIC_API_KEY/versions/latest"
